apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIWJPaFiJ5SIMwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjUwODE0MjM1MzM4WhcNMzUwODEyMjM1MzM4WjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOR23+LINnZok0mdWCsKiXAJlEdu1I7a
    otXRZwVWy2v219yypVMyZxqvilq4HyPVtepiup88tZCrsdotcbMVJFlaUGQsmnQy
    hvN68g8EyMqJ3ncDV+m8DWbx4WarYX4obyBlOZi+YfUHJw7jcltUCtDMP3GuCkmo
    qXhGaxpUvPp1EO2pQquCDUTrMBOQyFh0Epa4dW9DeS9DZ2WdNk7Lffz+whW7PqP7
    etXfYKfc+yv9eIn6FH8w7mME5URrbG+9Avh1T3bsPnTalHuaT3/CSecEIpBPQWK1
    8Rd+Je1qNiC/bvNyYDoSiPxLDh1zsYIZ7vN+GENoZsNSB/wv2HZwoVkCAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFMGw
    tNOZa7uSnR16Rv8UQC90k5FmMA0GCSqGSIb3DQEBCwUAA4IBAQBj7YzObAOaihd3
    yRayTdFGU6CTkx7ZCjil/gQ3vJk0wMamK/++2+sAjIir6PLlG/bhWktgxIOJ8bwk
    SOHqYPFObqpcGzLnE3//15UvPUZB2HVp/K5Yf/32YoVSZcFozoiMIlY/naH6LXsT
    ZdOoK/ukDN1SCMPxTpQXXPF09fQQbEVjPczgzO+96xY+edtbzpvfPoWW2HieIGlp
    7HXBdZ1czCSZ2KgTZ/jZESJaw39ZC8jwTrueFLoma4UICvG6rXOxmxOGlYUGQeRj
    aTgSiSc42nh/AX+Z/eMTH0PoR6tUvZzrDd+Q1S+2hFBC/ciYKLMOKPGX0xJaiomr
    lWkhOkJA
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIITyyNY16bFEkwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTI1MDgxNDIzNTMzOFoXDTM1MDgxMjIzNTMzOFowPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9/MykA9ytA6X
    aXqzXU11cdTVjgUcGG5rlERn3SC6KVn/SfLFXlAqzrrQw3Pqbq1gEEVnWIequCyg
    UMukQpwCkMO8Bpa+EXxjaTReCByIMkug5MCd+Gvq+496L988Fo5yKGTDlxQRDi2+
    l1wiH9QXO/nrLK+zvO7krIZe0KGXeGx60LopY01I2n+f2mI5gJe55fC9xJHSLtK8
    XH+Y+xMUR0zB6XfasQdYykZ1G0ks8VVmxDkJ6yZCqr3aOqDCAAgYCkxj3dCkBbNy
    Hb9jEz5sjk7fcAfhZsk+UfH7UuqGk+jb/3KIX00gVJ+CoqS41dZHbooM2Qnk+DH1
    rLqb67LNhwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUllK8zJdGDVqFdaTpGQi5WfI+HFUwDQYJKoZIhvcNAQELBQAD
    ggEBAF/kRcb4/TLFO4hCOUtREZK9USHw+CH+F475N7+nS3vbBkBk+l6QbT7VgH4J
    axjt51KiCbZyWPMMOMeuZVTG1K76DLvVN8csRxzqDFV8fpD6M1hLECACsTmU/2sR
    lAsHx6wIO7FBI+Kc0q0JPZ23m47u6r488/f7BsI/JDGoBXibVgAJldsdtBZaHO+K
    OdATT09sZ1Lms4tpAWBhFYMyG7hw/o1oogQKRpF7D30AcPd2ez3/VsVww6Gdkjvz
    d2WQD/w7giu4KI74VWKFBUREGOf5ZkEse4rTjFFmwwEBjg9GqvI9CV5O7mnOSBGK
    i8wx911OWF97KsLyWZhODhBF7xs=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIID8AlXM1P5j8wDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTI1MDgxNDIzNTMzOFoXDTM1MDgxMjIzNTMzOFowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEApKBFlmg/nhPborwC1Jyzjuqg7RdDc9bZ/7BzK9b824f5YeQxVB/UXo3WC/OD
    6v7XAOjFwPF36ifQ/stW89y2rxf4Ch9+w9QDT+2//AqIvfosJUjkanGcpTh05pUy
    sDqKVnytkUTzV0qynxHOYuOmTg9NVeY0sEnTz/36K5H3mS5kgDuNSNxMEy9TEilq
    4+c9Gmq6fqV5qgK3vCXW1Fo9tNkShPDEXFMpX/RDEk47EQa37XoTLrhkEebLfPa8
    /B27h9recbqUcyMa56cE/eAttPHrWZi/omAvynSo113FW9sBg5lNuRa9PcaIgiNW
    36TklVNqjazc42P1IvRwOCo2NwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUvLrIC+zZOaba8+Jf8Gr16rmLiWYwDQYJ
    KoZIhvcNAQELBQADggEBACNDTQr4Lq363cklyP8nBVCyGG37pHUvVVYU9hSw8usm
    wPWkapyxTw631sKJW9KD0xRl1dJ5Hb9/b31QiKh3e29P17Hp25PoF6vaCJRhQJLu
    pIQwjNpLAeptvyFyCdXoppJkxeom/Om8wGQvZFxigZxg/wQxZzTpdc5jTV/9a4jD
    74bndtX+1FuJ0JmSrzIXkMTKq04JNFnJ2m6uOgyC8mPo5vcxWvnY8mSxHgE0jwZt
    +78izMeHO1EaXdRFPTQj3lpcZ40X2oLU80OjzN7+kjDrXQGcDjOGq1jU6RmI9LQw
    4kZxT9EohSSmjfHZA3VqUelgJCOATsC0NdLEeNckFrY=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIDaESkZ0GWYkwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNzU1MjE2NDQ1MB4XDTI1MDgxNTAwMDcy
    NFoXDTM1MDgxMzAwMDcyNVowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNzU1MjE2NDQ1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1kMt
    u4L8OC59BRyap3s1Oez8VtSKxcKUfD/ZN6GWklPCNmYBN24RMuoNnF3i4IMEbPsB
    DyHA1A56XF4oBcJ8qqoHnJg4KCZzWzMzizT3cl33IuoGySp93eKL6InxHOKYzVu3
    fT0c4RjF1I8Whwfogx1sjTE/vg9IqNUck06sSqaU9oNaDomzudng1G1/4Dt6X/2f
    RRa/x2kJhgFbjE3NwmuEhNguygf/WYW6p0KtSmaXbogmdw4URpCe5t7uGVkFR/YD
    kXj3mnz96pXz+l/rrjpwZJIpbKkC6cJDwmwgv4vyRMTesm27N/JnMpdd6+9nO+/c
    La2uQSCRCT7KHAWqewIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUienINzjmqCZEq7N20aVmgN3icLcwHwYDVR0jBBgw
    FoAUienINzjmqCZEq7N20aVmgN3icLcwDQYJKoZIhvcNAQELBQADggEBAC+S4f7A
    OweVEG63hqxYz9EBzE6VaoDuOcuMD5ZebbBhz5oYOWpRjhFRRuDLsoFr7zSknEhI
    2D/h0QCWYhiyyxaP1hVgVIAyMQoVwPVzVtlHBXhl0R5leD+WxgCoR9PUJ/gkXcGV
    3ie2u0J/s4sZwskNTzLJpgow/d13Bd+yNfqZXUmfdUqHXjQKx/kyeGznj30A840h
    qfT19p3exLfOVdj9OttCHWUctjYthBHCsihFiV4sGBMYRR9L0ocZXL7s2UOHUlvg
    hKGkI4GQPE05o16WFVRfGD2azuCmdpoK98P+ejoS4ZsX72OM1Uo/EGK5lCik0uNo
    T4NX7KQS5G654/c=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIG7DCCBVSgAwIBAgIRAL2j4eQhcaLqUHhPduVt4hQwDQYJKoZIhvcNAQELBQAw
    UTELMAkGA1UEBhMCQ0ExGDAWBgNVBAoTD0VudHJ1c3QgTGltaXRlZDEoMCYGA1UE
    AxMfRW50cnVzdCBEViBUTFMgSXNzdWluZyBSU0EgQ0EgMjAeFw0yNTA4MTgwMDAw
    MDBaFw0yNjA4MTgyMzU5NTlaMCMxITAfBgNVBAMMGCouYXBwcy5vY3AyLmtvaGxl
    cmNvLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO9IldaVt1qB
    NdpGRk8fWpAPzTXYd52mKUzIgRS8WNpXMHfyIXV8r9/n5GUPvqaHXRKmbEBU/0MP
    BQjmfy5EeE8yL/qx2J6HaUcIUTAMUDs1bhIYAb53vh0vZnt33S/B49mggGmktluW
    CmZ56x79HbSQJ1BU/U674DMmd5Ws+73ELFhXuW+m03Oo4F1F7UG5V5mFkYlHk96v
    SX0czO15SaGx37NgJ7Fylz3+dD70mp5YWbhc2jo7l354zqpnJvExr5PJtV34M6Cm
    AZ9AqLSEf70Cs9QCh7K2OZcAKjlFoqi0UHCHuSrGVRMgV7x4KDRm3QO8K7ebhdWp
    MssArl7biJkCAwEAAaOCA2swggNnMB8GA1UdIwQYMBaAFI1CSTdAuUeVgJi+qbk6
    a/DNlqGDMB0GA1UdDgQWBBR38s1q9zIohDgJvWJkd2yhFFLj0DAOBgNVHQ8BAf8E
    BAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwEwYDVR0gBAwwCjAIBgZngQwBAgEwdQYIKwYBBQUHAQEEaTBnMEAGCCsGAQUF
    BzAChjRodHRwOi8vY3J0LnNlY3RpZ28uY29tL0VudHJ1c3REVlRMU0lzc3VpbmdS
    U0FDQTIuY3J0MCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTCC
    AX4GCisGAQQB1nkCBAIEggFuBIIBagFoAHYA2AlVO5RPev/IFhlvlE+Fq7D4/F6H
    VSYPFdEucrtFSxQAAAGYvvrNlQAABAMARzBFAiEAiIftY05exEA2nPQN4ht/oBlr
    96dqLfD93Lwd5+WPVEsCICahD13AsyIEO+aF/WIzsNLXh28hDVtHsF9EIYvwvW8y
    AHYArKswcGzr7IQx9BPS9JFfER5CJEOx8qaMTzwrO6ceAsMAAAGYvvrNWwAABAMA
    RzBFAiEAiRIOOyso5qoO8zuiQpoTB9+5FugJBq/jvCAxItydr5oCIBJvwRy+GJV1
    EMRtRvICU0DfNJdxD27A6xwjqeEU+fwVAHYA1219ENGn9XfCx+lf1wC/+YLJM1pl
    4dCzAXMXwMjFaXcAAAGYvvrNNgAABAMARzBFAiARXm/nuez8JC1wj4qVZiWrqgSm
    ROamrKvUPuVTVMpnCAIhAMgcSF33EcU9DqRz5xvNM+V42lT2XctHifXW1UUqtNYK
    MIHZBgNVHREEgdEwgc6CGCouYXBwcy5vY3AyLmtvaGxlcmNvLmNvbYITKi5vY3Ay
    LmtvaGxlcmNvLmNvbYIZYXBpLWludC5vY3AyLmtvaGxlcmNvLmNvbYIVYXBpLm9j
    cDIua29obGVyY28uY29tgjBjb25zb2xlLW9wZW5zaGlmdC1jb25zb2xlLmFwcHMu
    b2NwMi5rb2hsZXJjby5jb22CJm9hdXRoLW9wZW5zaGlmdC5hcHBzLm9jcDIua29o
    bGVyY28uY29tghFvY3AyLmtvaGxlcmNvLmNvbTANBgkqhkiG9w0BAQsFAAOCAYEA
    CXzM90MC1Tiy9ihLPEMc227hMXiASdtQ9l0fWYdl3hHhNi1NzP+bF6gp3lPjbgHz
    2ZgBnpfUzW7ar/34uHVppP70KkaEsVGsYmXe+P8IPeZbdX7vuS6FSo4qFVecq55c
    ggncptPwG7JX+swwOZfU0xXlWrXcSRN/VBMDhnFzd77TyFn30V09zJaOoqF6BZ6R
    nhgvtPoSKbqtoph8bywB2fTbf2aP15pa2pLHJJKSRLQBLCeWEIHGaHJ5Ovm5Fwr5
    8vKSJcvRbl43ARENqEUBbTiGj7V47txcO6+nqasqDLtYGQ0nW5pNse+UY46qjz21
    SBlMedrcasy5AFF13uEN/s6EV5oyfN3Bbd2cwuzenOUo2cqon6WF9SbODVGXzgl2
    sBWPPnor75tMituP+7mko0C19f4OtztqYUVdIl06loX/B9paGiHFPM3skBhXZP5q
    gpijhcUyE8hiVOHYsMTq3jGPkbHX6/KuFwG1qrDmapZd+ARpL7GQN4YnvzZt1qd/
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the kube-apiserver when using internal endpoints such as the internal service IP or kubernetes.default.svc. No other usage is guaranteed across distributions of Kubernetes clusters.
  creationTimestamp: "2025-08-18T21:05:03Z"
  name: kube-root-ca.crt
  namespace: designcenter
  resourceVersion: "2948218"
  uid: 13d5bd94-d2ae-4f8c-8177-3d15d3cc73cf
apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIILmC0YtGeoC8wDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc1NTIxNjQ0NTAe
    Fw0yNTA4MTUwMDA3MjRaFw0yNzEwMTQwMDA3MjVaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NTUyMTY0NDUwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDhTmMxwCWOT559+Ti3AKtRVjSAdlOUxAh6
    c74q9zkCq2aPDzPtJoZmxKsRc7HmVPdMwUYNm0cE/grHJJR2Cwv/PgMen2rCujeA
    Hj4up2d4h9al5LH1CaVUJnN/DOBqsfeJGRZrBAjyyl4ArvQ0ycp2BFCXLKdjN3M9
    9DBKxT5Bb1suq7LLcHnK6AkyBpOnijRDpoNPHHElco7i0vRzXLbiAWLf8DDdxpmu
    lWflsRa34io1nlVAa4XyIeg6TjUeDW/kFyvHkk/xs1Zo5+4LeiaVUElqA1yrJ91Z
    L8v+JoH+B7NjhZzC2xZNfa1sWA1PoRYUeSCuUIWa3NKYkrWxSeghAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSwpyUV
    NjlJNgP0MPp05+DboBu/4zAfBgNVHSMEGDAWgBSwpyUVNjlJNgP0MPp05+DboBu/
    4zANBgkqhkiG9w0BAQsFAAOCAQEA1ZZUTn/xzSd1GElGJQ3Ny5bE+akYEl2MGtuv
    wCaIu+HsOrg+yHxKbjq9TVOXStoNMgNpVk10oooJQD2zUfioqGVcea1kxK4f+yFl
    bgBe132bsudvky1OzOgfyouQL5MtfvSOkA1hceBEuSYW6zEBoY2hTk9vmDGKBHEh
    BCTZfGf2cUYXchkVUbB0St40ICg5p9PsVhBpFWuKUrD2doF9e6OAO6bBU8thSL8b
    N2XWWV1iFyHUOMh3Tci896JqaH+LuLAqoP+tsKdA5SYqI/sUaCRvbSU+IizNHrzb
    CrxrThp2E1kEjvqSAQhHXHbtK4Sb+CXOAArl0P8lpBr5Ntt4vw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: "2025-08-18T21:05:03Z"
  name: openshift-service-ca.crt
  namespace: designcenter
  resourceVersion: "2933707"
  uid: 6b7e717b-d380-421a-b953-aae7e193476d
