apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: dockerhub-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: balance-fit-prd/dockerhub-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fs-crane2-stunnel-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: fs-crane2-stunnel-client-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: balance-fit-prd/fs-crane2-stunnel-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: block-crane2-stunnel-client-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: block-crane2-stunnel-client-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: balance-fit-prd/block-crane2-stunnel-client-secret
