apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-store
  namespace: balance-fit-prd
spec:
  provider:
    vault:
      server: https://vault-vault.apps.ocp2.kohlerco.com
      path: apps
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
