apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: balance-fit-prd-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rich-p-ai/kohler-apps.git
    targetRevision: HEAD
    path: environments/dev/balance-fit-prd/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: balance-fit-prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
