apiVersion: v1
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIITIVtSb2j6+owDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTczMzE1Mjg3MzAe
    Fw0yNDEyMDIxNTIxMTNaFw0yNzAxMzExNTIxMTRaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3MzMxNTI4NzMwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvF116ZJx+OS6PVmR1Tso8Za7uhgQeL9Nt
    yGugZZA8piY2id5DsscRvHaSsKy3SdLWW72KJWkPZjSrgWCbo440cDa4RGRj0VTd
    I71v3EMXRqJdQTMUNDuLIaAJk6Cgr7GSpSaHUepC9V8E167Nxn67eXFwCq6l//8J
    iymeSLSEQ+gzOw/qzW/iOUrpAG3pC3nxNW5WpRhRq/4RTZhIE4BLt28rRDiJpeQb
    ZA+BNfl50GRKFt+8Fk7gk1nLgX1SBcrGSWhrUvuYWwwZ5qeI2YEYahMk4Sr1mcl5
    yLU1a3uU7EOilsDVLKt9hoWAP6ROib5jYaLE1dZTIOyxO1EHAwdlAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTlzTzj
    1jrdSM0hN4iQ8NZ+mLvOCTAfBgNVHSMEGDAWgBTlzTzj1jrdSM0hN4iQ8NZ+mLvO
    CTANBgkqhkiG9w0BAQsFAAOCAQEAXkbZkhImp3Lp0ItvhvlcTPBCFG6nrq82QiXN
    EwtnCX/Q9fdr8r5Bdu+ZIRn16526IiBuFkzMRnI0vzXqs+2kmOxkCmcPkbj7cs30
    2u5NSjo8Xglk9zE9+mxPlkBtc3SIKrA/CiK/DjFeq/orK6uNw5nN+X6CZeBbuXsh
    Ujf/lWQ74wyYOSgSNnm78DfXPTlVGlSUR0jzio/qmYbKmFIjB7MErPUOaVVUGp8K
    O60DtRr3zIJd4bWQ9eXagjQnXDF0cnaP17FyQkvQKfRO6VNKVGlkOuXsXzbTVmfs
    rnp4nqHDbmG47oZHc1P7boqGqbRLO9J2xyVgTNKMOHsZqaXMNg==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: openshift-service-ca.crt
  namespace: balance-fit-prd
