apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    openshift.io/backup-registry-hostname: image-registry.openshift-image-registry.svc:5000
    openshift.io/backup-server-version: "1.25"
    openshift.io/migration-registry: ""
    openshift.io/restore-registry-hostname: image-registry.openshift-image-registry.svc:5000
    openshift.io/restore-server-version: "1.29"
  labels:
    app: mysql-app
    migration.openshift.io/migrated-by-migmigration: 0ed510f5-66f0-409c-a1a0-c7e18d3d47ff
    migration.openshift.io/migrated-by-migplan: bd694ade-91df-4eac-8fe7-e614f02f8274
    velero.io/backup-name: migration-1e0ed-initial-sbf8k
    velero.io/restore-name: migration-1e0ed-final-c9chn
  name: mysql-app
  namespace: balance-fit-prd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql-app
      name: mysql-app
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: efit
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: mysql-app
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: mysql-app
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          name: mysql-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
