apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: "2025-06-30T12:47:03Z"
  name: nginx-unprivileged
  namespace: balance-fit-prd
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: quay.apps.ocp.kohlerco.com/kohler-base-images/nginx-unprivileged:latest
      generation: 1
      importPolicy:
        importMode: Legacy
      name: latest
      referencePolicy:
        type: Source
