apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  labels:
    app: mysql
    component: storage
    environment: production
  name: mysql-data
  namespace: balance-fit-prd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
  volumeName: pvc-50df19b7-7cb5-44c9-b672-4366c0e7f4f2
