apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.kubernetes.io/storage-provisioner: openshift-storage.rbd.csi.ceph.com
  labels:
    app: balance-fit
    component: storage
    environment: production
  name: app-data
  namespace: balance-fit-prd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-ceph-rbd
  volumeMode: Filesystem
  volumeName: pvc-b374dcf1-5073-4638-9ab2-e55bf88ac172
