apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: directvolumemigration-rsync-transfer
    app.kubernetes.io/part-of: openshift-migration
    directvolumemigration: 967f6a03-b630-419e-b618-9b69e01d0284
    migration.openshift.io/migrated-by-migplan: bd694ade-91df-4eac-8fe7-e614f02f8274
    owner: directvolumemigration
    purpose: rsync
  name: dvm
  namespace: balance-fit-prd
spec:
  host: dvm-balance-fit-prd.apps.ocp-prd.kohlerco.com
  port:
    targetPort: 6443
  subdomain: apps.ocp-prd.kohlerco.com
  tls:
    termination: passthrough
  to:
    kind: Service
    name: dvm
    weight: 100
  wildcardPolicy: None
