apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/migration-registry: ""
  labels:
    migration.openshift.io/migrated-by-migmigration: 0ed510f5-66f0-409c-a1a0-c7e18d3d47ff
    migration.openshift.io/migrated-by-migplan: bd694ade-91df-4eac-8fe7-e614f02f8274
    velero.io/backup-name: migration-1e0ed-initial-sbf8k
    velero.io/restore-name: migration-1e0ed-final-c9chn
  name: efit
  namespace: balance-fit-prd
spec:
  host: efit-prd.apps.ocp4.kohlerco.com
  port:
    targetPort: nginx-service
  to:
    kind: Service
    name: nginx-service
    weight: 100
  wildcardPolicy: None
