apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/version: 1.0.0
    cluster: ocp-prd
    environment: production
  labels:
    app: mysql
    app.kubernetes.io/instance: balance-fit-prod
    app.kubernetes.io/name: balance-fit
    app.kubernetes.io/part-of: balance-fit-stack
    component: database
    environment: production
  name: mysql-service
  namespace: balance-fit-prd
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
    app.kubernetes.io/name: balance-fit
    app.kubernetes.io/part-of: balance-fit-stack
    environment: production
  sessionAffinity: None
  type: ClusterIP
