apiVersion: v1
kind: Service
metadata:
  annotations:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/version: 1.0.0
    cluster: ocp-prd
    environment: production
  labels:
    app: efit
    app.kubernetes.io/instance: balance-fit-prod
    app.kubernetes.io/name: balance-fit
    app.kubernetes.io/part-of: balance-fit-stack
    component: backend
    environment: production
  name: efit
  namespace: balance-fit-prd
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: php-fpm
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: efit
    app.kubernetes.io/name: balance-fit
    app.kubernetes.io/part-of: balance-fit-stack
    environment: production
  sessionAffinity: None
  type: ClusterIP
