apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps.yaml
  - cronjobs.yaml
  - daemonsets.yaml
  - deploymentconfigs.yaml
  - deployments.yaml
  - imagestreams.yaml
  - jobs.yaml
  - pvcs.yaml
  - rolebindings.yaml
  - routes.yaml
  - services.yaml
  - statefulsets.yaml
