apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: efit
  namespace: balance-fit-prd
spec:
  clusterIP: 172.30.154.67
  clusterIPs:
    - 172.30.154.67
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: efit-service
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: efit
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: mysql-service
  namespace: balance-fit-prd
spec:
  clusterIP: 172.30.215.250
  clusterIPs:
    - 172.30.215.250
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mysql-app
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-app
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nginx-service
  namespace: balance-fit-prd
spec:
  clusterIP: 172.30.246.104
  clusterIPs:
    - 172.30.246.104
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: nginx-service
      port: 8030
      protocol: TCP
      targetPort: 8030
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
