apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: balance-fit-prd-prd

resources:
- ../../base

patchesStrategicMerge: []
- imagestreams.yaml
- routes.yaml
- persistentvolumeclaims.yaml
- deployments.yaml
- serviceaccounts.yaml
- services.yaml
- secrets.yaml
- configmaps.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/environment: production
    backup.kohlerco.com/timestamp: "20250729-151648"
